// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/test.proto

package test

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// FooRequest test
type FooRequest struct {
	A                    uint32   `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FooRequest) Reset()         { *m = FooRequest{} }
func (m *FooRequest) String() string { return proto.CompactTextString(m) }
func (*FooRequest) ProtoMessage()    {}
func (*FooRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc70169f84046e97, []int{0}
}

func (m *FooRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooRequest.Unmarshal(m, b)
}
func (m *FooRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FooRequest.Marshal(b, m, deterministic)
}
func (m *FooRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooRequest.Merge(m, src)
}
func (m *FooRequest) XXX_Size() int {
	return xxx_messageInfo_FooRequest.Size(m)
}
func (m *FooRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FooRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FooRequest proto.InternalMessageInfo

func (m *FooRequest) GetA() uint32 {
	if m != nil {
		return m.A
	}
	return 0
}

// FooReply test
type FooReply struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FooReply) Reset()         { *m = FooReply{} }
func (m *FooReply) String() string { return proto.CompactTextString(m) }
func (*FooReply) ProtoMessage()    {}
func (*FooReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc70169f84046e97, []int{1}
}

func (m *FooReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooReply.Unmarshal(m, b)
}
func (m *FooReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FooReply.Marshal(b, m, deterministic)
}
func (m *FooReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooReply.Merge(m, src)
}
func (m *FooReply) XXX_Size() int {
	return xxx_messageInfo_FooReply.Size(m)
}
func (m *FooReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FooReply.DiscardUnknown(m)
}

var xxx_messageInfo_FooReply proto.InternalMessageInfo

func (m *FooReply) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*FooRequest)(nil), "FooRequest")
	proto.RegisterType((*FooReply)(nil), "FooReply")
}

func init() { proto.RegisterFile("proto/test.proto", fileDescriptor_fc70169f84046e97) }

var fileDescriptor_fc70169f84046e97 = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x03, 0x33, 0x95, 0xa4, 0xb8, 0xb8, 0xdc, 0xf2, 0xf3,
	0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x78, 0xb8, 0x18, 0x13, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x78, 0x83, 0x18, 0x13, 0x95, 0xe4, 0xb8, 0x38, 0xc0, 0x72, 0x05, 0x39, 0x95, 0x42, 0x42,
	0x5c, 0x2c, 0xc9, 0xf9, 0x29, 0xa9, 0x50, 0x49, 0x30, 0xdb, 0x48, 0x83, 0x8b, 0x25, 0x04, 0xa4,
	0x4b, 0x81, 0x8b, 0x25, 0x38, 0x35, 0x2f, 0x45, 0x88, 0x5b, 0x0f, 0x61, 0x94, 0x14, 0xa7, 0x1e,
	0x4c, 0xaf, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x32, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8,
	0x76, 0xcf, 0x31, 0x80, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestClient is the client API for Test service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestClient interface {
	Send(ctx context.Context, in *FooRequest, opts ...grpc.CallOption) (*FooReply, error)
}

type testClient struct {
	cc *grpc.ClientConn
}

func NewTestClient(cc *grpc.ClientConn) TestClient {
	return &testClient{cc}
}

func (c *testClient) Send(ctx context.Context, in *FooRequest, opts ...grpc.CallOption) (*FooReply, error) {
	out := new(FooReply)
	err := c.cc.Invoke(ctx, "/Test/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServer is the server API for Test service.
type TestServer interface {
	Send(context.Context, *FooRequest) (*FooReply, error)
}

// UnimplementedTestServer can be embedded to have forward compatible implementations.
type UnimplementedTestServer struct {
}

func (*UnimplementedTestServer) Send(ctx context.Context, req *FooRequest) (*FooReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FooRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Test/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).Send(ctx, req.(*FooRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Test_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/test.proto",
}
